import { requireSuperAdminUser } from "@/src/lib/admin-auth";
import {
  getBackupImportDraft,
  type BackupCellDiff,
  type BackupImportDraft,
  type BackupImportError,
  type BackupRowDiff,
  type BackupTableDiff,
} from "@/src/lib/admin-data/backup";
import {
  DataEditorHeader,
  getSingleValue,
  StatusMessage,
} from "../AdminDataView";
import {
  confirmBackupImportAction,
  uploadBackupWorkbookAction,
} from "./actions";

type PageProps = {
  searchParams: Promise<{
    draft?: string | string[];
    error?: string | string[];
    success?: string | string[];
  }>;
};

export default async function AdminDataBackupPage({
  searchParams,
}: PageProps) {
  const actor = await requireSuperAdminUser();
  const query = await searchParams;
  const draftToken = getSingleValue(query.draft);
  const draft = draftToken ? getBackupImportDraft(draftToken, actor) : null;
  const draftExpired = Boolean(draftToken && !draft);

  return (
    <main className="flex-1 px-4 py-6 sm:px-6 sm:py-8 lg:px-10">
      <DataEditorHeader
        title="Backup & Restore"
        description="Download a full admin data workbook, validate an edited workbook, and apply approved changes to SQLite."
      />
      <StatusMessage
        error={
          getSingleValue(query.error) ??
          (draftExpired ? "Import draft expired or was not found." : undefined)
        }
        success={getSingleValue(query.success)}
      />

      <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <section className="rounded-lg border border-black/5 bg-surface px-4 py-5 sm:px-5">
          <div>
            <h2 className="text-base font-semibold text-ink">
              Download Backup
            </h2>
            <p className="mt-1 text-xs leading-5 text-ink/55">
              Exports users, facility content, time slots, and bookings in the
              required restore format.
            </p>
          </div>
          <div className="mt-5">
            <a
              href="/admin/data/backup/export"
              download
              className="inline-flex h-9 items-center justify-center rounded-md bg-brand px-4 text-sm font-medium text-white hover:bg-brand/90"
            >
              Export Excel
            </a>
          </div>
        </section>

        <section className="rounded-lg border border-black/5 bg-surface px-4 py-5 sm:px-5">
          <div>
            <h2 className="text-base font-semibold text-ink">
              Validate Workbook
            </h2>
            <p className="mt-1 text-xs leading-5 text-ink/55">
              Upload a workbook generated by this page. The database is not
              changed until the preview is confirmed.
            </p>
          </div>
          <form action={uploadBackupWorkbookAction} className="mt-5 space-y-4">
            <input
              type="file"
              name="workbook"
              accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
              required
              className="block w-full rounded-md border border-black/10 bg-white px-3 py-2 text-sm text-ink file:mr-3 file:rounded-md file:border-0 file:bg-surface file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-ink/70"
            />
            <div className="flex justify-end">
              <button
                type="submit"
                className="rounded-md bg-brand px-4 py-2 text-sm font-medium text-white hover:bg-brand/90"
              >
                Validate Excel
              </button>
            </div>
          </form>
        </section>
      </div>

      {draft && <BackupDraftPreview draft={draft} />}
    </main>
  );
}

function BackupDraftPreview({ draft }: { draft: BackupImportDraft }) {
  const { payload } = draft;
  const totalChanges = payload.diff.reduce(
    (sum, table) => sum + table.changes.length,
    0,
  );
  const hasErrors = payload.errors.length > 0;

  return (
    <section className="mt-7 rounded-lg border border-black/5 px-4 py-5 sm:px-5">
      <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h2 className="text-base font-semibold text-ink">
            Validation Preview
          </h2>
          <p className="mt-1 text-xs leading-5 text-ink/55">
            Draft expires at {draft.expiresAt}.
          </p>
        </div>
        {!hasErrors && totalChanges > 0 && (
          <form action={confirmBackupImportAction}>
            <input type="hidden" name="draftToken" value={draft.token} />
            <button
              type="submit"
              className="rounded-md bg-red-700 px-4 py-2 text-sm font-medium text-white hover:bg-red-800"
            >
              Apply Restore
            </button>
          </form>
        )}
      </div>

      {hasErrors ? (
        <ValidationErrors errors={payload.errors} />
      ) : (
        <>
          <div className="mb-5 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900">
            Applying this restore makes the uploaded workbook the source of
            truth for users, time slots, and bookings. Review the changes before
            continuing.
          </div>
          <DiffSummary diff={payload.diff} />
        </>
      )}
    </section>
  );
}

function ValidationErrors({ errors }: { errors: BackupImportError[] }) {
  return (
    <div className="rounded-md border border-red-200 bg-red-50 px-4 py-3">
      <h3 className="text-sm font-semibold text-red-900">
        Fix these errors before applying
      </h3>
      <ul className="mt-3 space-y-2 text-sm text-red-800">
        {errors.map((error, index) => (
          <li key={`${error.message}-${index}`}>
            {formatErrorLocation(error)}
            {error.message}
          </li>
        ))}
      </ul>
    </div>
  );
}

function DiffSummary({ diff }: { diff: BackupTableDiff[] }) {
  const totalChanges = diff.reduce((sum, table) => sum + table.changes.length, 0);

  if (totalChanges === 0) {
    return (
      <div className="rounded-lg border border-black/5 bg-surface px-6 py-10 text-center text-sm text-ink/60">
        No changes detected.
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {diff.map((table) => (
        <div key={table.tableName} className="rounded-lg border border-black/5">
          <div className="flex flex-col gap-2 border-b border-black/5 bg-surface px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
            <h3 className="text-sm font-semibold text-ink">{table.label}</h3>
            <div className="flex flex-wrap gap-2 text-xs text-ink/60">
              <span>{table.inserted} added</span>
              <span>{table.updated} updated</span>
              <span>{table.deleted} deleted</span>
              <span>{table.unchanged} unchanged</span>
            </div>
          </div>
          {table.changes.length === 0 ? (
            <div className="px-4 py-4 text-sm text-ink/55">No changes.</div>
          ) : (
            <ul className="divide-y divide-black/5">
              {table.changes.map((change) => (
                <li key={`${change.kind}-${change.rowId}`} className="px-4 py-3">
                  <RowChange change={change} />
                </li>
              ))}
            </ul>
          )}
        </div>
      ))}
    </div>
  );
}

function RowChange({ change }: { change: BackupRowDiff }) {
  return (
    <div className="text-sm">
      <div className="font-medium text-ink">
        {formatChangeKind(change.kind)} row #{change.rowId}
      </div>
      {change.kind === "update" ? (
        <ul className="mt-2 space-y-1 text-xs leading-5 text-ink/65">
          {change.cells.map((cell) => (
            <li key={cell.columnName}>
              <CellDiff cell={cell} />
            </li>
          ))}
        </ul>
      ) : (
        <div className="mt-1 text-xs text-ink/55">
          {change.cells.length} columns affected
        </div>
      )}
    </div>
  );
}

function CellDiff({ cell }: { cell: BackupCellDiff }) {
  return (
    <>
      <span className="font-medium text-ink/75">{cell.columnName}</span>
      <span>: </span>
      <span>{formatValue(cell.before)}</span>
      <span>{" -> "}</span>
      <span>{formatValue(cell.after)}</span>
    </>
  );
}

function formatErrorLocation(error: BackupImportError): string {
  const parts = [
    error.tableName,
    error.rowNumber ? `row ${error.rowNumber}` : null,
    error.columnName,
  ].filter(Boolean);
  return parts.length > 0 ? `${parts.join(" / ")}: ` : "";
}

function formatChangeKind(kind: BackupRowDiff["kind"]): string {
  switch (kind) {
    case "insert":
      return "Add";
    case "update":
      return "Update";
    case "delete":
      return "Delete";
  }
}

function formatValue(value: string | number | null): string {
  if (value === null || value === "") return "(blank)";
  return String(value);
}
